# Site settings
title: Bruce Toy Room
# email: ascendbruce@gmail.com
description: "My works and notes on ruby, rails, git, ubuntu linux, mac os x, etc..."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://toyroom.bruce.net" # the base hostname & protocol for your site
twitter_username: BruceToyRoom
github_username:  ascendbruce

# Build settings
markdown: redcarpet
highlighter: rouge
paginate: 5
paginate_path: "/page-:num/"
timezone: Asia/Taipei

defaults:
  -
    scope:
      path: ""
    values:
      author: "Bruce Li"
