# Site settings
title: Bruce Toy Room
# email: ascendbruce@gmail.com
description: "My works and notes on ruby, rails, git, ubuntu linux, mac os x, etc..."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://toyroom.bruce.net" # the base hostname & protocol for your site
twitter_username: BruceToyRoom
github_username:  ascendbruce

# Build settings
markdown: redcarpet
highlighter: rouge
timezone: Asia/Taipei

exclude:
  - Gemfile
  - Gemfile.lock
  - .ruby-version
  - .gitignore
  - .git

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Bruce Li"
  -
    scope:
      path: "tw"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "en"
      type: "posts"
    values:
      layout: "post-en"
