# Site settings
title: Bruce Toy Room
# email: ascendbruce@gmail.com
description: "My works and notes on ruby, rails, git, ubuntu linux, mac os x, etc..."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://toyroom.bruceli.net" # the base hostname & protocol for your site
twitter_username: BruceToyRoom
github_username:  ascendbruce
og_image: "/images/default_og_image.jpg"

# Build settings
markdown: kramdown
highlighter: rouge
timezone: Asia/Taipei

kramdown:
  input:  GFM
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - wercker.yml
  - _config.yml
  - .ruby-version
  - .gitignore
  - .gitkeep
  - .git

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Bruce Li"
  -
    scope:
      path: "tw/_posts"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "en/_posts"
      type: "posts"
    values:
      layout: "post-en"
