url: "http://127.0.0.1:4001"

# start development server by running:
#
# jekyll liveserve --drafts --config _config.yml,_config-dev.yml -P 4001
plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  # Excluding Jekyll-feed in dev for faster regeneration, improving live-reload experience.
