# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Bruce 的玩具間 Blog"
# email: your-email@example.com
tagline: "技術+管理+生活雜記，總之就是我的部落格"
description: >- # this means to ignore newlines until "baseurl:"
  我的技術筆記、讀書心得、工作體悟、生活雜記等，內容集結自幾個先前分開經營的部落格。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.bruceli.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BruceToyRoom
github_username:  ascendbruce
linkedin_username:  ascendbruce
facebook_username: BruceToyRoom
youtube_username: BruceToyRoom
author: Bruce Li

markdown: CommonMarkGhPages
# markdown: kramdown

collections:
  labels:
    output: true
    permalink: /labels/:path

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Bruce Li"

header_pages:
  - about.md
  - now.md
  - follow-me-tw.md
  - support.md
  - search.html

# Build settings
show_excerpts: true
theme: minima
timezone: Asia/Taipei

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

# plugins settings
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

facebook:
  admins: 100000059775380

webmaster_verifications:
  bing: 093FD634ADFD4C6B3C1F43452A8F13E6

google_analytics: UA-3381674-19

twitter:
  username: ascendbruce

feed:
  path: https://follow.it/bruce-blog?pub
  categories:
    - tw
    - en
    - jp

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .git
  - .gitignore
  - .gitkeep
  - .jekyll-cache/
  - .ruby-version
  - .sass-cache/
  - _config.yml
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - node_modules/
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts
